security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        main_provider:
            entity:
                class: App\Entity\User

    role_hierarchy:
        ROLE_USER:    ROLE_USER
        ROLE_ADMIN:   [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_EXPLOIT: [ROLE_USER, ROLE_ADMIN]
        ROLE_RH:      [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_MASTER:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_MASTER: [ROLE_MASTER, ROLE_ALLOWED_TO_SWITCH]


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main_provider
            form_login:
                login_path: login
                check_path: login
                success_handler: redirect.after.login
            remember_me:
                secret:       '%kernel.secret%'
                lifetime:     15552000
                path:         /
                

    access_control:
        - { path: ^/geolocbus, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: /admin/annoncecar/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/conducteur/, roles: ROLE_USER}
        - { path: ^/admin, roles: [ROLE_EXPLOIT, ROLE_RH]}
        - { path: ^/,  roles: [ROLE_SUPER_MASTER, ROLE_RH] }

