index:
    path: /
    controller: App\Controller\MainController::index
consultation:
    path: /consultation
    controller: App\Controller\MainController::consultation
car:
    path: /car/{id}
    controller: App\Controller\MainController::car
    requirements:
        id: '\d+'

ajout_panne:
    path: /panne/{id}
    controller: App\Controller\MainController::panne
    requirements:
        id: '\d+'

recherche:
    path: /recherche
    controller: App\Controller\MainController::recherche

