index:
    path: /admin/ajouter-car
    controller: App\Controller\MainController::index


consultation:
    path: /consultation
    controller: App\Controller\MainController::consultation
car:
    path: /car/{id}
    controller: App\Controller\MainController::car
    requirements:
        id: '\d+'

ajout_panne:
    path: /admin/panne/{id}
    controller: App\Controller\MainController::addPanne
    requirements:
        id: '\d+'

recherche:
    path: /recherche
    controller: App\Controller\MainController::recherche

liste_panne:
    path: /
    controller: App\Controller\MainController::listePanne

edit_car:
    path: /admin/editcar/{id}
    controller: App\Controller\MainController::editCar
    requirements:
        id: '\d+'

mev_car:
    path: /admin/mevcar/{id}
    controller: App\Controller\MainController::mevCar
    requirements:
        id: '\d+'

annonce_car:
    path: /admin/annoncecar/{id}
    controller: App\Controller\MainController::annonceCar
    requirements:
        id: '\d+'

ajax_snippet_image_send:
    path: /ajax/snippet/image/send/{id}
    controller: App\Controller\MainController::ajaxSnippetImageSend
    methods: [GET, POST]
    requirements:
        id: '\d+'

ajax_snippet_image_carrosserie:
    path: /ajax/snippet/image/carrosserie/{id}
    controller: App\Controller\MainController::ajaxSnippetImageCarrosserie
    methods: [GET, POST]
    requirements:
        id: '\d+'

effacer_car:
    path: /admin/effacer-car/{id}
    controller: App\Controller\MainController::deleteCar
    requirements:
        id: '\d+'

edit_panne:
    path: /admin/edit-panne/{id}
    controller: App\Controller\MainController::editPanne
    requirements:
        id: '\d+'

edit_panne_ant:
    path: /admin/edit-panne-ant/{id}
    controller: App\Controller\MainController::editPanneAnt
    requirements:
        id: '\d+'

delete_panne:
    path: /delete_panne/{id}
    controller: App\Controller\MainController::deletePanne
    requirements:
        id: '\d+'

change_etat_car:
    path: /change_etat/{id}
    controller: App\Controller\MainController::changeEtatCar
    requirements:
        id: '\d+'
add_rubrique:
    path: /admin/addRubrique
    controller: App\Controller\MainController::addRubrique
edit_rubrique:
    path: /admin/edit-rubrique/{id}
    controller: App\Controller\MainController::editRubrique
delete_rubrique:
    path: /admin/delete-rubrique/{id}
    controller: App\Controller\MainController::deleteRubrique
login:
    path: /login
    controller: App\Controller\MainController::login

login_check:
    path: /login_check

logout:
    path: /logout
    controller: App\Controller\MainController::logout

register:
    path: /register
    defaults:
    controller: App\Controller\MainController::register

miseajour:
    path: /admin/mise-a-jour
    controller: App\Controller\MainController::miseajour

donnees_km:
    path: /admin/donneeskm
    controller: App\Controller\MainController::donneesKilometriques

etat_carrosseries:
    path: /admin/etatCarrosseries
    controller: App\Controller\MainController::etatCarrosseries

carrosserie_car:
    path: /admin/carosserie/{id}
    controller: App\Controller\MainController::carrosserieCar
    requirements:
        id: '\d+'

view_carrosserie_car:
    path: /admin/carrosserie/car/{id}
    controller: App\Controller\MainController::viewCarrosserieCar
    requirements:
        id: '\d+'

delete_carrosserie:
    path: /admin/sup/carrosserie/{id}
    controller: App\Controller\MainController::deleteCarrosserie
    requirements:
        id: '\d+'

edit_carrosserie:
    path: /admin/edit/carrosserie/{id}
    controller: App\Controller\MainController::editCarrosserie
    requirements:
        id: '\d+'